#ifndef ELEMENT_DATA_H
#define ELEMENT_DATA_H
const unsigned short PROGMEM ELEMENT_DATA_INDEX[] = {
7,
};

const unsigned char PROGMEM ELEMENT_DATA[] = {
ENEMY_CHOPPER,40,64,ENEMY_CHOPPER_LT,
ITEM_KEY,16,72,ITEM_KEY_SET,
ITEM_DOOR,104,136,ITEM_DOOR_CLOSED,
ENEMY_CHOPPER,56,144,ENEMY_CHOPPER_LT,
ENEMY_GRUNT,144,200,ENEMY_GRUNT_LT,
ENEMY_GRUNT,32,208,ENEMY_GRUNT_LT,
ENEMY_GRUNT,240,224,ENEMY_GRUNT_LT,

};

#endif
